--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-deployment
        image: naresh240/springboot-mysql:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
