---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "mysqldb.fullname" . }}
{{- with .Values.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "mysqldb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
