apiVersion: v2
name: springboot
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: mysqldb
  version: 0.1.0
  repository: https://raw.githubusercontent.com/naresh240/spring-boot-mysql-example/helm/helm
